export enum RouteName {
  Home = 'home',
  Recipe = 'recipe',
  NewRecipe = 'new-recipe',
  EditRecipe = 'edit-recipe',
  Recipes = 'recipes',
  DynamicRecipe = 'dynamic-recipe',
  NewDynamicRecipe = 'new-dynamic-recipe',
  EditDynamicRecipe = 'edit-dynamic-recipe',
  DynamicRecipes = 'dynamic-recipes',
  SignUp = 'sign-up',
  SignIn = 'sign-in',
  NotFound = 'not-found',
  ForgotPassword = 'forgot-password',
  ChangePassword = 'change-password',
}
